;;; alarm-clock-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from alarm-clock.el

(autoload 'alarm-clock-set "alarm-clock" "\
Set an alarm clock at time TIME.
MESSAGE will be shown when notifying at that time.
Auto-save the alarms if alarm-clock-auto-save is true.

(fn TIME MESSAGE)" t)
(autoload 'alarm-clock-list-view "alarm-clock" "\
Display the alarm clocks." t)
(autoload 'alarm-clock-stop "alarm-clock" "\
Stop sounding the current alarm." t)
(autoload 'alarm-clock-restore "alarm-clock" "\
Restore alarm clocks on startup." t)
(autoload 'alarm-clock-save "alarm-clock" "\
Save alarm clocks to the alarm clock cache file." t)
(register-definition-prefixes "alarm-clock" '("alarm-clock-"))

;;; End of scraped data

(provide 'alarm-clock-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; alarm-clock-autoloads.el ends here
