;;; all-the-icons-nerd-fonts-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from all-the-icons-nerd-fonts.el

(autoload 'all-the-icons-nerd-fonts-prefer "all-the-icons-nerd-fonts" "\
Replace any `all-the-icons' associations with `nerd-fonts'.
When LIST-VARS is set update LIST-VARS instead of the standard all-the-icons
list variables.

(fn &optional LIST-VARS)")
(register-definition-prefixes "all-the-icons-nerd-fonts" '("all-the-icons-nerd-fonts-"))

;;; End of scraped data

(provide 'all-the-icons-nerd-fonts-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; all-the-icons-nerd-fonts-autoloads.el ends here
