;;; melpa-upstream-visit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from melpa-upstream-visit.el

(autoload 'muv "melpa-upstream-visit" "\
`browse-url's (or at least tries to) the PACKAGE-NAME's homepage.

(fn PACKAGE-NAME)" t)
(register-definition-prefixes "melpa-upstream-visit" '("muv:"))

;;; End of scraped data

(provide 'melpa-upstream-visit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; melpa-upstream-visit-autoloads.el ends here
