;;; agent-shell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from agent-shell.el

(autoload 'agent-shell-make-agent-config "agent-shell" "\
Create an agent configuration alist.

Keyword arguments:
- IDENTIFIER: Symbol identifying agent type (e.g., \\='claude-code)
- MODE-LINE-NAME: Name to display in the mode line
- WELCOME-FUNCTION: Function to call for welcome message
- BUFFER-NAME: Name of the agent buffer
- SHELL-PROMPT: The shell prompt string
- SHELL-PROMPT-REGEXP: Regexp to match the shell prompt
- CLIENT-MAKER: Function to create the client
- NEEDS-AUTHENTICATION: Non-nil authentication is required
- AUTHENTICATE-REQUEST-MAKER: Function to create authentication requests
- DEFAULT-MODEL-ID: Default model ID (function returning value).
- DEFAULT-SESSION-MODE-ID: Default session mode ID (function returning value).
- ICON-NAME: Name of the icon to use
- INSTALL-INSTRUCTIONS: Instructions to show when executable is not found

Returns an alist with all specified values.

(fn &key IDENTIFIER MODE-LINE-NAME WELCOME-FUNCTION BUFFER-NAME SHELL-PROMPT SHELL-PROMPT-REGEXP CLIENT-MAKER NEEDS-AUTHENTICATION AUTHENTICATE-REQUEST-MAKER DEFAULT-MODEL-ID DEFAULT-SESSION-MODE-ID ICON-NAME INSTALL-INSTRUCTIONS)")
(autoload 'agent-shell "agent-shell" "\
Start or reuse an existing agent shell.

`agent-shell' carries some DWIM (do what I mean) behaviour.

If in a project without a shell, offer to create one.

If already in a shell, invoke `agent-shell-toggle'.

If a region is active or point is on relevant context (ie.
`dired' files or image buffers), carry them over to the
shell input.

See `agent-shell-context-sources' on how to control DWIM
behaviour.

With \\[universal-argument] prefix ARG, force start a new shell.

With \\[universal-argument] \\[universal-argument] prefix ARG, prompt to pick an existing shell.

(fn &optional ARG)" t)
(autoload 'agent-shell-toggle "agent-shell" "\
Toggle agent shell display." t)
(autoload 'agent-shell-new-shell "agent-shell" "\
Start a new agent shell.

Always prompts for agent selection, even if existing shells are available." t)
(autoload 'agent-shell-new-temp-shell "agent-shell" "\
Start a new agent shell in a temporary directory.

The directory is trashed when the shell buffer is killed.
When CONFIG is non-nil, use it instead of prompting for an agent.
When NO-DISPLAY is non-nil, don't display the shell buffer.

(fn &key CONFIG NO-DISPLAY)" t)
(autoload 'agent-shell-new-downloads-shell "agent-shell" "\
Start a new agent shell in ~/Downloads.

When CONFIG is non-nil, use it instead of prompting for an agent.
When NO-DISPLAY is non-nil, don't display the shell buffer.

(fn &key CONFIG NO-DISPLAY)" t)
(autoload 'agent-shell-restart "agent-shell" "\
Clear conversation by restarting the agent shell in the same project.

Kills the current shell buffer (shutting down the ACP client) and
starts a fresh shell with the same agent configuration.

When SESSION-ID is provided, resume that session instead of starting new.

Works from both shell and viewport buffers.

(fn &key SESSION-ID)" t)
(function-put 'agent-shell-restart 'command-modes '(agent-shell-mode agent-shell-viewport-view-mode agent-shell-viewport-edit-mode))
(autoload 'agent-shell-reload "agent-shell" "\
Reload the current session by restarting with the same session ID.

Works from both shell and viewport buffers." t)
(function-put 'agent-shell-reload 'command-modes '(agent-shell-mode agent-shell-viewport-view-mode agent-shell-viewport-edit-mode))
(autoload 'agent-shell-fork "agent-shell" "\
Fork the current session into a new shell.

Creates a new shell that forks the current session's conversation,
leaving the original shell intact.  The new shell shares conversation
history with the original but diverges from this point forward.

Works from both shell and viewport buffers." t)
(function-put 'agent-shell-fork 'command-modes '(agent-shell-mode agent-shell-viewport-view-mode agent-shell-viewport-edit-mode))
(autoload 'agent-shell-resume-session "agent-shell" "\
Resume an existing agent session by SESSION-ID.

Prompts for agent selection and starts a new shell that resumes
the session identified by SESSION-ID.

(fn SESSION-ID)" t)
(autoload 'agent-shell-prompt-compose "agent-shell" "\
Compose an `agent-shell' prompt in a dedicated buffer.

If currently visiting an `agent-shell', transfer latest input." t)
(autoload 'agent-shell-shell-buffer "agent-shell" "\
Return an agent-shell buffer for the current context.

A stable public API wrapping the internal resolver, intended for
packages that integrate with agent-shell programmatically.

Resolution order: viewport → current buffer → project buffers → prompt user.

Example:
  (agent-shell-shell-buffer)
  (agent-shell-shell-buffer :no-error t)

(fn &key VIEWPORT-BUFFER NO-ERROR NO-CREATE)")
(register-definition-prefixes "agent-shell" '("agent-shell-"))


;;; Generated autoloads from agent-shell-anthropic.el

(register-definition-prefixes "agent-shell-anthropic" '("agent-shell-anthropic-"))


;;; Generated autoloads from agent-shell-artist.el

(register-definition-prefixes "agent-shell-artist" '("agent-shell-artist-"))


;;; Generated autoloads from agent-shell-auggie.el

(register-definition-prefixes "agent-shell-auggie" '("agent-shell-auggie-"))


;;; Generated autoloads from agent-shell-cline.el

(register-definition-prefixes "agent-shell-cline" '("agent-shell-cline-"))


;;; Generated autoloads from agent-shell-codebuddy.el

(register-definition-prefixes "agent-shell-codebuddy" '("agent-shell-codebuddy-"))


;;; Generated autoloads from agent-shell-completion.el

(register-definition-prefixes "agent-shell-completion" '("agent-shell-"))


;;; Generated autoloads from agent-shell-config.el

(register-definition-prefixes "agent-shell-config" '("agent-shell--"))


;;; Generated autoloads from agent-shell-cursor.el

(register-definition-prefixes "agent-shell-cursor" '("agent-shell-cursor-"))


;;; Generated autoloads from agent-shell-devcontainer.el

(register-definition-prefixes "agent-shell-devcontainer" '("agent-shell-"))


;;; Generated autoloads from agent-shell-diff.el

(register-definition-prefixes "agent-shell-diff" '("agent-shell-diff-"))


;;; Generated autoloads from agent-shell-droid.el

(register-definition-prefixes "agent-shell-droid" '("agent-shell-droid-"))


;;; Generated autoloads from agent-shell-experimental.el

(register-definition-prefixes "agent-shell-experimental" '("agent-shell-experimental--"))


;;; Generated autoloads from agent-shell-github.el

(register-definition-prefixes "agent-shell-github" '("agent-shell-github-"))


;;; Generated autoloads from agent-shell-google.el

(register-definition-prefixes "agent-shell-google" '("agent-shell-google-"))


;;; Generated autoloads from agent-shell-goose.el

(register-definition-prefixes "agent-shell-goose" '("agent-shell-goose-"))


;;; Generated autoloads from agent-shell-hermes.el

(register-definition-prefixes "agent-shell-hermes" '("agent-shell-hermes-"))


;;; Generated autoloads from agent-shell-kimi.el

(register-definition-prefixes "agent-shell-kimi" '("agent-shell-kimi-"))


;;; Generated autoloads from agent-shell-kiro.el

(register-definition-prefixes "agent-shell-kiro" '("agent-shell-kiro-"))


;;; Generated autoloads from agent-shell-list-edit.el

(register-definition-prefixes "agent-shell-list-edit" '("agent-shell-list-edit-"))


;;; Generated autoloads from agent-shell-markdown.el

(register-definition-prefixes "agent-shell-markdown" '("agent-shell-markdown-"))


;;; Generated autoloads from agent-shell-mistral.el

(register-definition-prefixes "agent-shell-mistral" '("agent-shell-mistral-"))


;;; Generated autoloads from agent-shell-mock-agent.el

(register-definition-prefixes "agent-shell-mock-agent" '("agent-shell-mock-agent-"))


;;; Generated autoloads from agent-shell-omp.el

(register-definition-prefixes "agent-shell-omp" '("agent-shell-omp-"))


;;; Generated autoloads from agent-shell-openai.el

(register-definition-prefixes "agent-shell-openai" '("agent-shell-openai-"))


;;; Generated autoloads from agent-shell-opencode.el

(register-definition-prefixes "agent-shell-opencode" '("agent-shell-opencode-"))


;;; Generated autoloads from agent-shell-pi.el

(register-definition-prefixes "agent-shell-pi" '("agent-shell-pi-"))


;;; Generated autoloads from agent-shell-project.el

(register-definition-prefixes "agent-shell-project" '("agent-shell-"))


;;; Generated autoloads from agent-shell-qwen.el

(register-definition-prefixes "agent-shell-qwen" '("agent-shell-qwen-"))


;;; Generated autoloads from agent-shell-styles.el

(register-definition-prefixes "agent-shell-styles" '("agent-shell--"))


;;; Generated autoloads from agent-shell-ui.el

(autoload 'agent-shell-ui-mode "agent-shell-ui" "\
Minor mode for SUI block navigation.

This is a minor mode.  If called interactively, toggle the
`Agent-Shell-Ui mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `agent-shell-ui-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "agent-shell-ui" '("agent-shell-ui-"))


;;; Generated autoloads from agent-shell-usage.el

(register-definition-prefixes "agent-shell-usage" '("agent-shell-"))


;;; Generated autoloads from agent-shell-viewport.el

(register-definition-prefixes "agent-shell-viewport" '("agent-shell-viewport-"))


;;; Generated autoloads from agent-shell-worktree.el

(autoload 'agent-shell-new-worktree-shell "agent-shell-worktree" "\
Create a new git worktree and start an agent shell in it.

The worktree is created at <project-root>/.agent-shell/worktrees/<worktree-name>
where <worktree-name> is a randomly generated name (e.g., \"adoring-hawking\").

The user is prompted to confirm or edit the worktree path before creation." t)
(register-definition-prefixes "agent-shell-worktree" '("agent-shell-worktree--"))

;;; End of scraped data

(provide 'agent-shell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; agent-shell-autoloads.el ends here
